name: ds-minimal
channels:
  - defaults
  - conda-forge
dependencies:
  # Python version
  - python=3.11
  
  # Core data science packages
  - numpy=1.26.*
  - pandas=2.2.*
  - matplotlib=3.8.*
  - scipy=1.12.*
  - scikit-learn=1.4.*
  - seaborn=0.13.*
  
  # Jupyter ecosystem
  - jupyterlab=4.1.*
  - ipykernel=6.29.*
  - notebook=7.1.*
  
  # Essential utilities
  - requests=2.31.*
  - python-dateutil=2.9.*
  - pytz
  - httpx=0.25.*
  
  # Excel and data file support
  - openpyxl=3.1.*
  - xlrd=2.0.*
  - xlsxwriter=3.2.*
  - tabulate=0.9.*
  
  # Development tools
  - ipython=8.22.*
  - pip=24.*
  
  # Pip packages
  - pip:
    - uv>=0.1.0