name: ds-minimal  # Using same environment name to update it
channels:
  - defaults
  - conda-forge
dependencies:
  # Advanced visualization
  - seaborn=0.13.*
  - plotly=5.19.*
  - altair=5.2.*
  
  # Graph and network analysis
  - networkx=3.2.*
  
  # Web frameworks
  - streamlit=1.31.*
  
  # System utilities
  - psutil=5.9.*
  
  # Additional scientific computing
  - statsmodels=0.14.*
  - sympy=1.12.*
  
  # Image processing
  - pillow=10.2.*
  
  # Data formats
  - openpyxl=3.1.*
  - xlrd=2.0.*
  - h5py=3.10.*
  
  # Additional development tools
  - black=24.*
  - pylint=3.0.*
  
  # Performance tools
  - numba=0.59.*
  - cython=3.0.*
  
  # Machine learning extensions
  - xgboost=2.0.*
  - lightgbm=4.3.*
  
  # Time series
  - prophet=1.1.*
  
  # Natural language processing basics
  - nltk=3.8.*
  - spacy=3.7.*
  
  # Database connectors
  - sqlalchemy=2.0.*
  - pymongo=4.6.*
  - redis-py=5.0.*